export const SET_IS_LOADED = "SET_IS_LOADED";
export const SET_TABLE_DATA = "SET_TABLE_DATA";
export const SET_PARSED_HEADER = "SET_PARSED_HEADER";

export const FETCH_REPOS_BEGIN = "FETCH_REPOS_BEGIN";
export const FETCH_REPOS_SUCCESS = "FETCH_REPOS_SUCCESS";
export const FETCH_REPOS_FAILURE = "FETCH_REPOS_FAILURE";
